//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 xsd 自动生成, Version=4.0.30319.33440。
// 
namespace Mesnac.Interface.Webservice.MesInterface {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ll.com/DZMES")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ll.com/DZMES", IsNullable=false)]
    public partial class MT_DZECC_out {
        
        private string processCodeField;
        
        private MT_DZECC_outDN[] dNsField;
        
        private MT_DZECC_outReservation[] reservationsField;
        
        private MT_DZECC_outPlanDN[] planDNsField;
        
        private MT_DZECC_outMatDoc[] matDocsField;

        private MT_DZECC_outProductVersion[] productVersionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProcessCode {
            get {
                return this.processCodeField;
            }
            set {
                this.processCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MT_DZECC_outDN[] DNs {
            get {
                return this.dNsField;
            }
            set {
                this.dNsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Reservation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MT_DZECC_outReservation[] Reservations {
            get {
                return this.reservationsField;
            }
            set {
                this.reservationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PlanDN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MT_DZECC_outPlanDN[] PlanDNs {
            get {
                return this.planDNsField;
            }
            set {
                this.planDNsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MatDoc", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MT_DZECC_outMatDoc[] MatDocs {
            get {
                return this.matDocsField;
            }
            set {
                this.matDocsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ProductVersion", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public MT_DZECC_outProductVersion[] ProductVersions
        {
            get
            {
                return this.productVersionsField;
            }
            set
            {
                this.productVersionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ll.com/DZMES")]
    public partial class MT_DZECC_outDN {
        
        private MT_DZECC_outDNDNHeader[] dNHeaderField;
        
        private MT_DZECC_outDNDNItem[] dNItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DNHeader", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MT_DZECC_outDNDNHeader[] DNHeader {
            get {
                return this.dNHeaderField;
            }
            set {
                this.dNHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DNItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MT_DZECC_outDNDNItem[] DNItem {
            get {
                return this.dNItemField;
            }
            set {
                this.dNItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ll.com/DZMES")]
    public partial class MT_DZECC_outDNDNHeader {
        
        private string salOrdIDField;
        
        private string dNNoField;
        
        private string deliveryDateField;
        
        private string suppliercodeField;
        
        private string dummy1Field;
        
        private string dummy2Field;
        
        private string dummy3Field;
        
        private string dummy4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalOrdID {
            get {
                return this.salOrdIDField;
            }
            set {
                this.salOrdIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DNNo {
            get {
                return this.dNNoField;
            }
            set {
                this.dNNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DeliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Suppliercode {
            get {
                return this.suppliercodeField;
            }
            set {
                this.suppliercodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy1 {
            get {
                return this.dummy1Field;
            }
            set {
                this.dummy1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy2 {
            get {
                return this.dummy2Field;
            }
            set {
                this.dummy2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy3 {
            get {
                return this.dummy3Field;
            }
            set {
                this.dummy3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy4 {
            get {
                return this.dummy4Field;
            }
            set {
                this.dummy4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ll.com/DZMES")]
    public partial class MT_DZECC_outDNDNItem {
        
        private string dNItemField;
        
        private string salOrdItemField;
        
        private string matIDField;
        
        private string deliveryQtyField;
        
        private string referenceNoField;
        
        private string referenceItemField;
        
        private string lotNoField;
        
        private string plantField;
        
        private string storagelocField;
        
        private string dummy1Field;
        
        private string dummy2Field;
        
        private string dummy3Field;
        
        private string dummy4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DNItem {
            get {
                return this.dNItemField;
            }
            set {
                this.dNItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalOrdItem {
            get {
                return this.salOrdItemField;
            }
            set {
                this.salOrdItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatID {
            get {
                return this.matIDField;
            }
            set {
                this.matIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DeliveryQty {
            get {
                return this.deliveryQtyField;
            }
            set {
                this.deliveryQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReferenceNo {
            get {
                return this.referenceNoField;
            }
            set {
                this.referenceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReferenceItem {
            get {
                return this.referenceItemField;
            }
            set {
                this.referenceItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LotNo {
            get {
                return this.lotNoField;
            }
            set {
                this.lotNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Storageloc {
            get {
                return this.storagelocField;
            }
            set {
                this.storagelocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy1 {
            get {
                return this.dummy1Field;
            }
            set {
                this.dummy1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy2 {
            get {
                return this.dummy2Field;
            }
            set {
                this.dummy2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy3 {
            get {
                return this.dummy3Field;
            }
            set {
                this.dummy3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy4 {
            get {
                return this.dummy4Field;
            }
            set {
                this.dummy4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ll.com/DZMES")]
    public partial class MT_DZECC_outReservation {
        
        private string reserNoField;
        
        private string reserItemField;
        
        private string movTypeField;
        
        private string matCodeField;
        
        private string unitField;
        
        private string departmentField;
        
        private string qtyField;
        
        private string plantFromField;
        
        private string storLocFromField;
        
        private string plantToField;
        
        private string storLocToField;
        
        private string costCenterField;
        
        private string orderField;
        
        private string demondsDateField;
        
        private string batchField;
        
        private string dummy1Field;
        
        private string dummy2Field;
        
        private string dummy3Field;
        
        private string dummy4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReserNo {
            get {
                return this.reserNoField;
            }
            set {
                this.reserNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReserItem {
            get {
                return this.reserItemField;
            }
            set {
                this.reserItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MovType {
            get {
                return this.movTypeField;
            }
            set {
                this.movTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatCode {
            get {
                return this.matCodeField;
            }
            set {
                this.matCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PlantFrom {
            get {
                return this.plantFromField;
            }
            set {
                this.plantFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StorLocFrom {
            get {
                return this.storLocFromField;
            }
            set {
                this.storLocFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PlantTo {
            get {
                return this.plantToField;
            }
            set {
                this.plantToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StorLocTo {
            get {
                return this.storLocToField;
            }
            set {
                this.storLocToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CostCenter {
            get {
                return this.costCenterField;
            }
            set {
                this.costCenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DemondsDate {
            get {
                return this.demondsDateField;
            }
            set {
                this.demondsDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Batch {
            get {
                return this.batchField;
            }
            set {
                this.batchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy1 {
            get {
                return this.dummy1Field;
            }
            set {
                this.dummy1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy2 {
            get {
                return this.dummy2Field;
            }
            set {
                this.dummy2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy3 {
            get {
                return this.dummy3Field;
            }
            set {
                this.dummy3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy4 {
            get {
                return this.dummy4Field;
            }
            set {
                this.dummy4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ll.com/DZMES")]
    public partial class MT_DZECC_outPlanDN {
        
        private MT_DZECC_outPlanDNDNHeader[] dNHeaderField;
        
        private MT_DZECC_outPlanDNDNItem[] dNItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DNHeader", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MT_DZECC_outPlanDNDNHeader[] DNHeader {
            get {
                return this.dNHeaderField;
            }
            set {
                this.dNHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DNItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MT_DZECC_outPlanDNDNItem[] DNItem {
            get {
                return this.dNItemField;
            }
            set {
                this.dNItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ll.com/DZMES")]
    public partial class MT_DZECC_outPlanDNDNHeader {
        
        private string sNNoField;
        
        private string sRFlagField;
        
        private string docDateField;
        
        private string customerIDField;
        
        private string dummy1Field;
        
        private string dummy2Field;
        
        private string dummy3Field;
        
        private string dummy4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SNNo {
            get {
                return this.sNNoField;
            }
            set {
                this.sNNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SRFlag {
            get {
                return this.sRFlagField;
            }
            set {
                this.sRFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocDate {
            get {
                return this.docDateField;
            }
            set {
                this.docDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy1 {
            get {
                return this.dummy1Field;
            }
            set {
                this.dummy1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy2 {
            get {
                return this.dummy2Field;
            }
            set {
                this.dummy2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy3 {
            get {
                return this.dummy3Field;
            }
            set {
                this.dummy3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy4 {
            get {
                return this.dummy4Field;
            }
            set {
                this.dummy4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ll.com/DZMES")]
    public partial class MT_DZECC_outPlanDNDNItem {
        
        private string lineItemNoField;
        
        private string materialCodeField;
        
        private string plantField;
        
        private string storageLocField;
        
        private string qtyField;
        
        private string batchField;
        
        private string dummy1Field;
        
        private string dummy2Field;
        
        private string dummy3Field;
        
        private string dummy4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LineItemNo {
            get {
                return this.lineItemNoField;
            }
            set {
                this.lineItemNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaterialCode {
            get {
                return this.materialCodeField;
            }
            set {
                this.materialCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StorageLoc {
            get {
                return this.storageLocField;
            }
            set {
                this.storageLocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Batch {
            get {
                return this.batchField;
            }
            set {
                this.batchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy1 {
            get {
                return this.dummy1Field;
            }
            set {
                this.dummy1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy2 {
            get {
                return this.dummy2Field;
            }
            set {
                this.dummy2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy3 {
            get {
                return this.dummy3Field;
            }
            set {
                this.dummy3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy4 {
            get {
                return this.dummy4Field;
            }
            set {
                this.dummy4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ll.com/DZMES")]
    public partial class MT_DZECC_outMatDoc {
        
        private string matDocNOField;
        
        private string matDocItemField;
        
        private string movTypeField;
        
        private string materialCodeField;
        
        private string materialDescField;
        
        private string markField;
        
        private string materialSpecField;
        
        private string remarkField;
        
        private string docYearField;
        
        private string plantField;
        
        private string storageLocField;
        
        private string qtyField;
        
        private string unitField;
        
        private string receiverField;
        
        private string amountField;
        
        private string costCenterField;
        
        private string costCenterDecField;
        
        private string reserNoField;
        
        private string reserItemField;
        
        private string inputDateField;
        
        private string sourceDocField;
        
        private string postDateField;
        
        private string dummy1Field;
        
        private string dummy2Field;
        
        private string dummy3Field;
        
        private string dummy4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatDocNO {
            get {
                return this.matDocNOField;
            }
            set {
                this.matDocNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatDocItem {
            get {
                return this.matDocItemField;
            }
            set {
                this.matDocItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MovType {
            get {
                return this.movTypeField;
            }
            set {
                this.movTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaterialCode {
            get {
                return this.materialCodeField;
            }
            set {
                this.materialCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaterialDesc {
            get {
                return this.materialDescField;
            }
            set {
                this.materialDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaterialSpec {
            get {
                return this.materialSpecField;
            }
            set {
                this.materialSpecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocYear {
            get {
                return this.docYearField;
            }
            set {
                this.docYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StorageLoc {
            get {
                return this.storageLocField;
            }
            set {
                this.storageLocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CostCenter {
            get {
                return this.costCenterField;
            }
            set {
                this.costCenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CostCenterDec {
            get {
                return this.costCenterDecField;
            }
            set {
                this.costCenterDecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReserNo {
            get {
                return this.reserNoField;
            }
            set {
                this.reserNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReserItem {
            get {
                return this.reserItemField;
            }
            set {
                this.reserItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InputDate {
            get {
                return this.inputDateField;
            }
            set {
                this.inputDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SourceDoc {
            get {
                return this.sourceDocField;
            }
            set {
                this.sourceDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PostDate {
            get {
                return this.postDateField;
            }
            set {
                this.postDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy1 {
            get {
                return this.dummy1Field;
            }
            set {
                this.dummy1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy2 {
            get {
                return this.dummy2Field;
            }
            set {
                this.dummy2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy3 {
            get {
                return this.dummy3Field;
            }
            set {
                this.dummy3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy4 {
            get {
                return this.dummy4Field;
            }
            set {
                this.dummy4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ll.com/DZMES")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ll.com/DZMES", IsNullable=false)]
    public partial class NewDataSet {
        
        private MT_DZECC_out[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MT_DZECC_out")]
        public MT_DZECC_out[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ll.com/DZMES")]
    public partial class MT_DZECC_outProductVersion
    {

        private string materialCodeField;

        private string plantField;

        private string productionVerField;

        private string verDescField;

        private string costColStatusField;

        private string matStatusField;

        private string mkspField;

        private string dummy1Field;

        private string dummy2Field;

        private string dummy3Field;

        private string dummy4Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaterialCode
        {
            get
            {
                return this.materialCodeField;
            }
            set
            {
                this.materialCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Plant
        {
            get
            {
                return this.plantField;
            }
            set
            {
                this.plantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductionVer
        {
            get
            {
                return this.productionVerField;
            }
            set
            {
                this.productionVerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VerDesc
        {
            get
            {
                return this.verDescField;
            }
            set
            {
                this.verDescField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CostColStatus
        {
            get
            {
                return this.costColStatusField;
            }
            set
            {
                this.costColStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatStatus
        {
            get
            {
                return this.matStatusField;
            }
            set
            {
                this.matStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mksp
        {
            get
            {
                return this.mkspField;
            }
            set
            {
                this.mkspField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy1
        {
            get
            {
                return this.dummy1Field;
            }
            set
            {
                this.dummy1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy2
        {
            get
            {
                return this.dummy2Field;
            }
            set
            {
                this.dummy2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy3
        {
            get
            {
                return this.dummy3Field;
            }
            set
            {
                this.dummy3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy4
        {
            get
            {
                return this.dummy4Field;
            }
            set
            {
                this.dummy4Field = value;
            }
        }
    }
}
