//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 xsd 自动生成, Version=4.0.30319.33440。
// 
namespace Mesnac.Interface.Webservice.MesInterface
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ll.com/COMM")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ll.com/COMM", IsNullable = false)]
    public partial class MT_ReturnMSGs
    {

        private MT_ReturnMSGsReturnMSG[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReturnMSG", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MT_ReturnMSGsReturnMSG[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MT_ReturnMSGsReturnMSG
    {

        private MT_ReturnMSGsReturnMSGMSGHead mSGHeadField;

        private MT_ReturnMSGsReturnMSGMSGItem[] mSGItemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MSGHead", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MT_ReturnMSGsReturnMSGMSGHead MSGHead
        {
            get
            {
                return this.mSGHeadField;
            }
            set
            {
                this.mSGHeadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MSGItem", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MT_ReturnMSGsReturnMSGMSGItem[] MSGItem
        {
            get
            {
                return this.mSGItemField;
            }
            set
            {
                this.mSGItemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MT_ReturnMSGsReturnMSGMSGHead
    {

        private string mSGIDField;

        private string bUSIDField;

        private string bUSTYPField;

        private string tLDIDField;

        private string tLGNAMField;

        private string dTSENDField;

        private string sENDERField;

        private string rECIEVERField;

        private string dUMMY1Field;

        private string dUMMY2Field;

        private string dUMMY3Field;

        private string dUMMY4Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID
        {
            get
            {
                return this.mSGIDField;
            }
            set
            {
                this.mSGIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUSID
        {
            get
            {
                return this.bUSIDField;
            }
            set
            {
                this.bUSIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUSTYP
        {
            get
            {
                return this.bUSTYPField;
            }
            set
            {
                this.bUSTYPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TLDID
        {
            get
            {
                return this.tLDIDField;
            }
            set
            {
                this.tLDIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TLGNAM
        {
            get
            {
                return this.tLGNAMField;
            }
            set
            {
                this.tLGNAMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DTSEND
        {
            get
            {
                return this.dTSENDField;
            }
            set
            {
                this.dTSENDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SENDER
        {
            get
            {
                return this.sENDERField;
            }
            set
            {
                this.sENDERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RECIEVER
        {
            get
            {
                return this.rECIEVERField;
            }
            set
            {
                this.rECIEVERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DUMMY1
        {
            get
            {
                return this.dUMMY1Field;
            }
            set
            {
                this.dUMMY1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DUMMY2
        {
            get
            {
                return this.dUMMY2Field;
            }
            set
            {
                this.dUMMY2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DUMMY3
        {
            get
            {
                return this.dUMMY3Field;
            }
            set
            {
                this.dUMMY3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DUMMY4
        {
            get
            {
                return this.dUMMY4Field;
            }
            set
            {
                this.dUMMY4Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MT_ReturnMSGsReturnMSGMSGItem
    {

        private string sERIDField;

        private string mSTYPField;

        private string eRRDESField;

        private string sAPIDField;

        private string dOCTYField;

        private string dUMMY1Field;

        private string dUMMY2Field;

        private string dUMMY3Field;

        private string dUMMY4Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SERID
        {
            get
            {
                return this.sERIDField;
            }
            set
            {
                this.sERIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSTYP
        {
            get
            {
                return this.mSTYPField;
            }
            set
            {
                this.mSTYPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERRDES
        {
            get
            {
                return this.eRRDESField;
            }
            set
            {
                this.eRRDESField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SAPID
        {
            get
            {
                return this.sAPIDField;
            }
            set
            {
                this.sAPIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOCTY
        {
            get
            {
                return this.dOCTYField;
            }
            set
            {
                this.dOCTYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DUMMY1
        {
            get
            {
                return this.dUMMY1Field;
            }
            set
            {
                this.dUMMY1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DUMMY2
        {
            get
            {
                return this.dUMMY2Field;
            }
            set
            {
                this.dUMMY2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DUMMY3
        {
            get
            {
                return this.dUMMY3Field;
            }
            set
            {
                this.dUMMY3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DUMMY4
        {
            get
            {
                return this.dUMMY4Field;
            }
            set
            {
                this.dUMMY4Field = value;
            }
        }
    }
}
