//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 xsd 自动生成, Version=4.0.30319.33440。
// 
namespace Mesnac.Interface.Entity.SapEntity
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ll.com/DZMES")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ll.com/DZMES", IsNullable=false)]
    public partial class DT_MES_out {
        
        private string processCodeField;

        private DT_MES_outDN[] dNsField;

        private DT_MES_outReservation[] reservationsField;

        private DT_MES_outPlanDN[] planDNsField;

        private DT_MES_outRetunMSG[] returnMSGsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProcessCode {
            get {
                return this.processCodeField;
            }
            set {
                this.processCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DN", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DT_MES_outDN[] DNs
        {
            get
            {
                return this.dNsField;
            }
            set
            {
                this.dNsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Reservation", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DT_MES_outReservation[] Reservations
        {
            get
            {
                return this.reservationsField;
            }
            set
            {
                this.reservationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PlanDN", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DT_MES_outPlanDN[] PlanDNs
        {
            get
            {
                return this.planDNsField;
            }
            set
            {
                this.planDNsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RetunMSG", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DT_MES_outRetunMSG[] ReturnMSGs
        {
            get
            {
                return this.returnMSGsField;
            }
            set
            {
                this.returnMSGsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ll.com/DZMES")]
    public partial class DT_MES_outDN
    {

        private DT_MES_outDNDNHeader[] dNHeaderField;

        private DT_MES_outDNDNItems[] dNItemsField;

        private DT_MES_outReservation[] reservationsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DNHeader", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_MES_outDNDNHeader[] DNHeader
        {
            get
            {
                return this.dNHeaderField;
            }
            set
            {
                this.dNHeaderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DNItems", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_MES_outDNDNItems[] DNItems
        {
            get
            {
                return this.dNItemsField;
            }
            set
            {
                this.dNItemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ll.com/DZMES")]
    public partial class DT_MES_outDNDNHeader
    {

        private string salOrdIDField;

        private string dNNoField;

        private string deliveryDateField;

        private string suppliercodeField;

        private string dummy1Field;

        private string dummy2Field;

        private string dummy3Field;

        private string dummy4Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalOrdID
        {
            get
            {
                return this.salOrdIDField;
            }
            set
            {
                this.salOrdIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DNNo
        {
            get
            {
                return this.dNNoField;
            }
            set
            {
                this.dNNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DeliveryDate
        {
            get
            {
                return this.deliveryDateField;
            }
            set
            {
                this.deliveryDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Suppliercode
        {
            get
            {
                return this.suppliercodeField;
            }
            set
            {
                this.suppliercodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy1
        {
            get
            {
                return this.dummy1Field;
            }
            set
            {
                this.dummy1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy2
        {
            get
            {
                return this.dummy2Field;
            }
            set
            {
                this.dummy2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy3
        {
            get
            {
                return this.dummy3Field;
            }
            set
            {
                this.dummy3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy4
        {
            get
            {
                return this.dummy4Field;
            }
            set
            {
                this.dummy4Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ll.com/DZMES")]
    public partial class DT_MES_outDNDNItems
    {

        private string dNItemField;

        private string salOrdItemField;

        private string matIDField;

        private string deliveryQtyField;

        private string referenceNoField;

        private string referenceItemField;

        private string lotNoField;

        private string plantField;

        private string storagelocField;

        private string dummy1Field;

        private string dummy2Field;

        private string dummy3Field;

        private string dummy4Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DNItem
        {
            get
            {
                return this.dNItemField;
            }
            set
            {
                this.dNItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalOrdItem
        {
            get
            {
                return this.salOrdItemField;
            }
            set
            {
                this.salOrdItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatID
        {
            get
            {
                return this.matIDField;
            }
            set
            {
                this.matIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DeliveryQty
        {
            get
            {
                return this.deliveryQtyField;
            }
            set
            {
                this.deliveryQtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReferenceNo
        {
            get
            {
                return this.referenceNoField;
            }
            set
            {
                this.referenceNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReferenceItem
        {
            get
            {
                return this.referenceItemField;
            }
            set
            {
                this.referenceItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LotNo
        {
            get
            {
                return this.lotNoField;
            }
            set
            {
                this.lotNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Plant
        {
            get
            {
                return this.plantField;
            }
            set
            {
                this.plantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Storageloc
        {
            get
            {
                return this.storagelocField;
            }
            set
            {
                this.storagelocField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy1
        {
            get
            {
                return this.dummy1Field;
            }
            set
            {
                this.dummy1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy2
        {
            get
            {
                return this.dummy2Field;
            }
            set
            {
                this.dummy2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy3
        {
            get
            {
                return this.dummy3Field;
            }
            set
            {
                this.dummy3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy4
        {
            get
            {
                return this.dummy4Field;
            }
            set
            {
                this.dummy4Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ll.com/DZMES")]
    public partial class DT_MES_outReservation
    {

        private string reserNoField;

        private string reserItemField;

        private string movTypeField;

        private string matCodeField;

        private string unitField;

        private string departmentField;

        private string qtyField;

        private string plantFromField;

        private string storLocFromField;

        private string plantToField;

        private string storLocToField;

        private string costCenterField;

        private string orderField;

        private string demondsDateField;

        private string batchField;

        private string dummy1Field;

        private string dummy2Field;

        private string dummy3Field;

        private string dummy4Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReserNo
        {
            get
            {
                return this.reserNoField;
            }
            set
            {
                this.reserNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReserItem
        {
            get
            {
                return this.reserItemField;
            }
            set
            {
                this.reserItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MovType
        {
            get
            {
                return this.movTypeField;
            }
            set
            {
                this.movTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatCode
        {
            get
            {
                return this.matCodeField;
            }
            set
            {
                this.matCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PlantFrom
        {
            get
            {
                return this.plantFromField;
            }
            set
            {
                this.plantFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StorLocFrom
        {
            get
            {
                return this.storLocFromField;
            }
            set
            {
                this.storLocFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PlantTo
        {
            get
            {
                return this.plantToField;
            }
            set
            {
                this.plantToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StorLocTo
        {
            get
            {
                return this.storLocToField;
            }
            set
            {
                this.storLocToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CostCenter
        {
            get
            {
                return this.costCenterField;
            }
            set
            {
                this.costCenterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DemondsDate
        {
            get
            {
                return this.demondsDateField;
            }
            set
            {
                this.demondsDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Batch
        {
            get
            {
                return this.batchField;
            }
            set
            {
                this.batchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy1
        {
            get
            {
                return this.dummy1Field;
            }
            set
            {
                this.dummy1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy2
        {
            get
            {
                return this.dummy2Field;
            }
            set
            {
                this.dummy2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy3
        {
            get
            {
                return this.dummy3Field;
            }
            set
            {
                this.dummy3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy4
        {
            get
            {
                return this.dummy4Field;
            }
            set
            {
                this.dummy4Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ll.com/DZMES")]
    public partial class DT_MES_outPlanDN
    {

        private DT_MES_outPlanDNDNHeader dNHeaderField;

        private DT_MES_outPlanDNDNItem[] dNItemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DNHeader", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_MES_outPlanDNDNHeader DNHeader
        {
            get
            {
                return this.dNHeaderField;
            }
            set
            {
                this.dNHeaderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DNItem", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_MES_outPlanDNDNItem[] DNItem
        {
            get
            {
                return this.dNItemField;
            }
            set
            {
                this.dNItemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ll.com/DZMES")]
    public partial class DT_MES_outPlanDNDNHeader
    {

        private string sNNoField;

        private string sRFlagField;

        private string docDateField;

        private string customerIDField;

        private string dummy1Field;

        private string dummy2Field;

        private string dummy3Field;

        private string dummy4Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SNNo
        {
            get
            {
                return this.sNNoField;
            }
            set
            {
                this.sNNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SRFlag
        {
            get
            {
                return this.sRFlagField;
            }
            set
            {
                this.sRFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocDate
        {
            get
            {
                return this.docDateField;
            }
            set
            {
                this.docDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerID
        {
            get
            {
                return this.customerIDField;
            }
            set
            {
                this.customerIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy1
        {
            get
            {
                return this.dummy1Field;
            }
            set
            {
                this.dummy1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy2
        {
            get
            {
                return this.dummy2Field;
            }
            set
            {
                this.dummy2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy3
        {
            get
            {
                return this.dummy3Field;
            }
            set
            {
                this.dummy3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy4
        {
            get
            {
                return this.dummy4Field;
            }
            set
            {
                this.dummy4Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ll.com/DZMES")]
    public partial class DT_MES_outPlanDNDNItem
    {

        private string lineItemNoField;

        private string materialCodeField;

        private string plantField;

        private string storageLocField;

        private string qtyField;

        private string batchField;

        private string dummy1Field;

        private string dummy2Field;

        private string dummy3Field;

        private string dummy4Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LineItemNo
        {
            get
            {
                return this.lineItemNoField;
            }
            set
            {
                this.lineItemNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaterialCode
        {
            get
            {
                return this.materialCodeField;
            }
            set
            {
                this.materialCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Plant
        {
            get
            {
                return this.plantField;
            }
            set
            {
                this.plantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StorageLoc
        {
            get
            {
                return this.storageLocField;
            }
            set
            {
                this.storageLocField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Batch
        {
            get
            {
                return this.batchField;
            }
            set
            {
                this.batchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy1
        {
            get
            {
                return this.dummy1Field;
            }
            set
            {
                this.dummy1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy2
        {
            get
            {
                return this.dummy2Field;
            }
            set
            {
                this.dummy2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy3
        {
            get
            {
                return this.dummy3Field;
            }
            set
            {
                this.dummy3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy4
        {
            get
            {
                return this.dummy4Field;
            }
            set
            {
                this.dummy4Field = value;
            }
        }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ll.com/DZMES")]
    public partial class DT_MES_outRetunMSG
    {

        private DT_MES_outRetunMSGMSGHead[] mSGHeadField;

        private DT_MES_outRetunMSGMSGItem[] mSGItemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MSGHead", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_MES_outRetunMSGMSGHead[] MSGHead
        {
            get
            {
                return this.mSGHeadField;
            }
            set
            {
                this.mSGHeadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MSGItem", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_MES_outRetunMSGMSGItem[] MSGItem
        {
            get
            {
                return this.mSGItemField;
            }
            set
            {
                this.mSGItemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ll.com/DZMES")]
    public partial class DT_MES_outRetunMSGMSGHead
    {

        private string mSGIDField;

        private string bUSIDField;

        private string bUSTYPField;

        private string tLDIDField;

        private string tLGNAMField;

        private string dTSENDField;

        private string sENDERField;

        private string rECIEVERField;

        private string dummy1Field;

        private string dummy2Field;

        private string dummy3Field;

        private string dummy4Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID
        {
            get
            {
                return this.mSGIDField;
            }
            set
            {
                this.mSGIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUSID
        {
            get
            {
                return this.bUSIDField;
            }
            set
            {
                this.bUSIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUSTYP
        {
            get
            {
                return this.bUSTYPField;
            }
            set
            {
                this.bUSTYPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TLDID
        {
            get
            {
                return this.tLDIDField;
            }
            set
            {
                this.tLDIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TLGNAM
        {
            get
            {
                return this.tLGNAMField;
            }
            set
            {
                this.tLGNAMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DTSEND
        {
            get
            {
                return this.dTSENDField;
            }
            set
            {
                this.dTSENDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SENDER
        {
            get
            {
                return this.sENDERField;
            }
            set
            {
                this.sENDERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RECIEVER
        {
            get
            {
                return this.rECIEVERField;
            }
            set
            {
                this.rECIEVERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy1
        {
            get
            {
                return this.dummy1Field;
            }
            set
            {
                this.dummy1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy2
        {
            get
            {
                return this.dummy2Field;
            }
            set
            {
                this.dummy2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy3
        {
            get
            {
                return this.dummy3Field;
            }
            set
            {
                this.dummy3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy4
        {
            get
            {
                return this.dummy4Field;
            }
            set
            {
                this.dummy4Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ll.com/DZMES")]
    public partial class DT_MES_outRetunMSGMSGItem
    {

        private string seridField;

        private string mSTYPField;

        private string eRRDESField;

        private string sAPIDField;

        private string dOCTYField;

        private string dummy1Field;

        private string dummy2Field;

        private string dummy3Field;

        private string dummy4Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Serid
        {
            get
            {
                return this.seridField;
            }
            set
            {
                this.seridField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSTYP
        {
            get
            {
                return this.mSTYPField;
            }
            set
            {
                this.mSTYPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERRDES
        {
            get
            {
                return this.eRRDESField;
            }
            set
            {
                this.eRRDESField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SAPID
        {
            get
            {
                return this.sAPIDField;
            }
            set
            {
                this.sAPIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOCTY
        {
            get
            {
                return this.dOCTYField;
            }
            set
            {
                this.dOCTYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy1
        {
            get
            {
                return this.dummy1Field;
            }
            set
            {
                this.dummy1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy2
        {
            get
            {
                return this.dummy2Field;
            }
            set
            {
                this.dummy2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy3
        {
            get
            {
                return this.dummy3Field;
            }
            set
            {
                this.dummy3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dummy4
        {
            get
            {
                return this.dummy4Field;
            }
            set
            {
                this.dummy4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ll.com/DZMES")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ll.com/DZMES", IsNullable=false)]
    public partial class NewDataSet {
        
        private DT_MES_out[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DT_MES_out")]
        public DT_MES_out[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
