//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3655
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.42。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "SI_Comm_outBinding", Namespace = "http://ll.com/COMM")]
public partial class SI_Comm_outService : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback SI_Comm_outOperationCompleted;

    /// <remarks/>
    public SI_Comm_outService()
    {
        this.Url = "http://pici.linglong.cn:30000/XISOAPAdapter/MessageServlet?channel=:BC_COMM_Soap_" +
            "out:CC_COMM_Soap_out&version=3.0&Sender.Service=BC_COMM_Soap_out&Interface=http%" +
            "3A%2F%2Fll.com%2FCOMM%5ESI_Comm_out";
    }

    /// <remarks/>
    public event SI_Comm_outCompletedEventHandler SI_Comm_outCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay = true, Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    public void SI_Comm_out([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://ll.com/COMM")] DT_Comm_in MT_Comm_out)
    {
        this.Invoke("SI_Comm_out", new object[] {
                    MT_Comm_out});
    }

    /// <remarks/>
    public System.IAsyncResult BeginSI_Comm_out(DT_Comm_in MT_Comm_out, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("SI_Comm_out", new object[] {
                    MT_Comm_out}, callback, asyncState);
    }

    /// <remarks/>
    public void EndSI_Comm_out(System.IAsyncResult asyncResult)
    {
        this.EndInvoke(asyncResult);
    }

    /// <remarks/>
    public void SI_Comm_outAsync(DT_Comm_in MT_Comm_out)
    {
        this.SI_Comm_outAsync(MT_Comm_out, null);
    }

    /// <remarks/>
    public void SI_Comm_outAsync(DT_Comm_in MT_Comm_out, object userState)
    {
        if ((this.SI_Comm_outOperationCompleted == null))
        {
            this.SI_Comm_outOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_Comm_outOperationCompleted);
        }
        this.InvokeAsync("SI_Comm_out", new object[] {
                    MT_Comm_out}, this.SI_Comm_outOperationCompleted, userState);
    }

    private void OnSI_Comm_outOperationCompleted(object arg)
    {
        if ((this.SI_Comm_outCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SI_Comm_outCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ll.com/COMM")]
public partial class DT_Comm_in
{

    private Rphead rpheadField;

    private DT_GoodsMovements_inGoodsMovement[] goodsMovementsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Rphead Rphead
    {
        get
        {
            return this.rpheadField;
        }
        set
        {
            this.rpheadField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("GoodsMovement", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public DT_GoodsMovements_inGoodsMovement[] GoodsMovements
    {
        get
        {
            return this.goodsMovementsField;
        }
        set
        {
            this.goodsMovementsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ll.com/COMM")]
public partial class Rphead
{

    private string mSGIDField;

    private string bUSIDField;

    private string bUSTYPField;

    private string tLDIDField;

    private string tLGNAMField;

    private string dTSENDField;

    private string sENDERField;

    private string rECIEVERField;

    private string dummy1Field;

    private string dummy2Field;

    private string dummy3Field;

    private string dummy4Field;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGID
    {
        get
        {
            return this.mSGIDField;
        }
        set
        {
            this.mSGIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BUSID
    {
        get
        {
            return this.bUSIDField;
        }
        set
        {
            this.bUSIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BUSTYP
    {
        get
        {
            return this.bUSTYPField;
        }
        set
        {
            this.bUSTYPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TLDID
    {
        get
        {
            return this.tLDIDField;
        }
        set
        {
            this.tLDIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TLGNAM
    {
        get
        {
            return this.tLGNAMField;
        }
        set
        {
            this.tLGNAMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DTSEND
    {
        get
        {
            return this.dTSENDField;
        }
        set
        {
            this.dTSENDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SENDER
    {
        get
        {
            return this.sENDERField;
        }
        set
        {
            this.sENDERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RECIEVER
    {
        get
        {
            return this.rECIEVERField;
        }
        set
        {
            this.rECIEVERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Dummy1
    {
        get
        {
            return this.dummy1Field;
        }
        set
        {
            this.dummy1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Dummy2
    {
        get
        {
            return this.dummy2Field;
        }
        set
        {
            this.dummy2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Dummy3
    {
        get
        {
            return this.dummy3Field;
        }
        set
        {
            this.dummy3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Dummy4
    {
        get
        {
            return this.dummy4Field;
        }
        set
        {
            this.dummy4Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ll.com/COMM")]
public partial class DT_GoodsMovements_inGoodsMovement
{

    private DT_GoodsMovements_inGoodsMovementMovHeader movHeaderField;

    private DT_GoodsMovements_inGoodsMovementMoveItem[] moveItemField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_GoodsMovements_inGoodsMovementMovHeader MovHeader
    {
        get
        {
            return this.movHeaderField;
        }
        set
        {
            this.movHeaderField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MoveItem", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DT_GoodsMovements_inGoodsMovementMoveItem[] MoveItem
    {
        get
        {
            return this.moveItemField;
        }
        set
        {
            this.moveItemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ll.com/COMM")]
public partial class DT_GoodsMovements_inGoodsMovementMovHeader
{

    private string docDateField;

    private string postDateField;

    private string headTXTField;

    private string refDocField;

    private string dummy1Field;

    private string dummy2Field;

    private string dummy3Field;

    private string dummy4Field;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DocDate
    {
        get
        {
            return this.docDateField;
        }
        set
        {
            this.docDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PostDate
    {
        get
        {
            return this.postDateField;
        }
        set
        {
            this.postDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HeadTXT
    {
        get
        {
            return this.headTXTField;
        }
        set
        {
            this.headTXTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RefDoc
    {
        get
        {
            return this.refDocField;
        }
        set
        {
            this.refDocField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Dummy1
    {
        get
        {
            return this.dummy1Field;
        }
        set
        {
            this.dummy1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Dummy2
    {
        get
        {
            return this.dummy2Field;
        }
        set
        {
            this.dummy2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Dummy3
    {
        get
        {
            return this.dummy3Field;
        }
        set
        {
            this.dummy3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Dummy4
    {
        get
        {
            return this.dummy4Field;
        }
        set
        {
            this.dummy4Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ll.com/COMM")]
public partial class DT_GoodsMovements_inGoodsMovementMoveItem
{

    private string movTypeField;

    private string materialCodeField;

    private string plantFromField;

    private string storageLocField;

    private string batchField;

    private string barCodeField;

    private string specialIndField;

    private string qtyField;

    private string unitField;

    private string poField;

    private string pOItemField;

    private string movIndField;

    private string dnField;

    private string dNItemField;

    private string recMatField;

    private string recPlantField;

    private string recStoLocField;

    private string recBatchField;

    private string costCenterField;

    private string internalORDField;

    private string movReasonField;

    private string itemTxtField;

    private string recieverField;

    private string stockTypField;

    private string completeFlagField;

    private string reservationField;

    private string reservItemField;

    private string vendorField;

    private string customerField;

    private string refDocYearField;

    private string refDocField;

    private string rEFDocItemField;

    private string dummy1Field;

    private string dummy2Field;

    private string dummy3Field;

    private string dummy4Field;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MovType
    {
        get
        {
            return this.movTypeField;
        }
        set
        {
            this.movTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MaterialCode
    {
        get
        {
            return this.materialCodeField;
        }
        set
        {
            this.materialCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PlantFrom
    {
        get
        {
            return this.plantFromField;
        }
        set
        {
            this.plantFromField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StorageLoc
    {
        get
        {
            return this.storageLocField;
        }
        set
        {
            this.storageLocField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Batch
    {
        get
        {
            return this.batchField;
        }
        set
        {
            this.batchField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BarCode
    {
        get
        {
            return this.barCodeField;
        }
        set
        {
            this.barCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SpecialInd
    {
        get
        {
            return this.specialIndField;
        }
        set
        {
            this.specialIndField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Qty
    {
        get
        {
            return this.qtyField;
        }
        set
        {
            this.qtyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PO
    {
        get
        {
            return this.poField;
        }
        set
        {
            this.poField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string POItem
    {
        get
        {
            return this.pOItemField;
        }
        set
        {
            this.pOItemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MovInd
    {
        get
        {
            return this.movIndField;
        }
        set
        {
            this.movIndField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DN
    {
        get
        {
            return this.dnField;
        }
        set
        {
            this.dnField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DNItem
    {
        get
        {
            return this.dNItemField;
        }
        set
        {
            this.dNItemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RecMat
    {
        get
        {
            return this.recMatField;
        }
        set
        {
            this.recMatField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RecPlant
    {
        get
        {
            return this.recPlantField;
        }
        set
        {
            this.recPlantField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RecStoLoc
    {
        get
        {
            return this.recStoLocField;
        }
        set
        {
            this.recStoLocField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RecBatch
    {
        get
        {
            return this.recBatchField;
        }
        set
        {
            this.recBatchField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CostCenter
    {
        get
        {
            return this.costCenterField;
        }
        set
        {
            this.costCenterField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InternalORD
    {
        get
        {
            return this.internalORDField;
        }
        set
        {
            this.internalORDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MovReason
    {
        get
        {
            return this.movReasonField;
        }
        set
        {
            this.movReasonField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ItemTxt
    {
        get
        {
            return this.itemTxtField;
        }
        set
        {
            this.itemTxtField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Reciever
    {
        get
        {
            return this.recieverField;
        }
        set
        {
            this.recieverField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StockTyp
    {
        get
        {
            return this.stockTypField;
        }
        set
        {
            this.stockTypField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CompleteFlag
    {
        get
        {
            return this.completeFlagField;
        }
        set
        {
            this.completeFlagField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Reservation
    {
        get
        {
            return this.reservationField;
        }
        set
        {
            this.reservationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReservItem
    {
        get
        {
            return this.reservItemField;
        }
        set
        {
            this.reservItemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Vendor
    {
        get
        {
            return this.vendorField;
        }
        set
        {
            this.vendorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Customer
    {
        get
        {
            return this.customerField;
        }
        set
        {
            this.customerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RefDocYear
    {
        get
        {
            return this.refDocYearField;
        }
        set
        {
            this.refDocYearField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RefDoc
    {
        get
        {
            return this.refDocField;
        }
        set
        {
            this.refDocField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string REFDocItem
    {
        get
        {
            return this.rEFDocItemField;
        }
        set
        {
            this.rEFDocItemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Dummy1
    {
        get
        {
            return this.dummy1Field;
        }
        set
        {
            this.dummy1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Dummy2
    {
        get
        {
            return this.dummy2Field;
        }
        set
        {
            this.dummy2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Dummy3
    {
        get
        {
            return this.dummy3Field;
        }
        set
        {
            this.dummy3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Dummy4
    {
        get
        {
            return this.dummy4Field;
        }
        set
        {
            this.dummy4Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void SI_Comm_outCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
